version: '3'

services:
  nav:
    # Starts the navigation stack
    image: ros:noetic-ros-base
    depends_on:
      - master
      - mqtt
      - mqtt-ros-bridge
      - rosserial
      - differential-drive
      - node-red

  catkin:
    image: ros:noetic-ros-base
    tty: true
    container_name: catkin
    volumes:
      - ./:/working-directory
    working_dir: /working-directory
    command: /bin/bash

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
      - "1901:1901"
    volumes:
      - ./mqtt-config:/mosquitto/config
      - .mqtt/data:/mosquitto/data
      - .mqtt/log:/mosquitto/log

  master:
    image: ros:noetic-ros-base
    container_name: master
    ports:
      - "11311:11311"
    volumes:
      - .ros_logs/master:/root/.ros/
    deploy:
      restart_policy:
        condition: any
    command: roscore

  turtlesim:
    container_name: turtlesim
    environment:
      - DISPLAY=192.168.1.190:0.0
      - ROS_MASTER_URI=http://master:11311
    volumes:
      - .ros_logs/turtlesim:/root/.ros/
    build: dockerfiles/turtlesim
    command: rosrun turtlesim turtlesim_node

  rqt-gui:
    container_name: rqt-gui
    environment:
      - DISPLAY=192.168.1.190:0.0
      - ROS_MASTER_URI=http://master:11311
    volumes:
      - .ros_logs/rqt-gui:/root/.ros/
      - ./differential-drive-configs/rqt-configs:/root/rqt-configs
    build: dockerfiles/rqt-gui
    command: rosrun rqt_gui rqt_gui -s reconfigure

  rqt-plot:
    container_name: rqt-plot
    environment:
      - DISPLAY=192.168.1.190:0.0
      - ROS_MASTER_URI=http://master:11311
    volumes:
      - .ros_logs/rqt-plot:/root/.ros/
    build: dockerfiles/rqt-plot
    command: rqt_plot

  rqt:
    container_name: rqt
    environment:
      - DISPLAY=192.168.1.190:0.0
      - ROS_MASTER_URI=http://master:11311
    volumes:
      - .ros_logs/rqt:/root/.ros/
      - .rqt-data:/root/
    build: dockerfiles/rqt-plot
    command: rqt

  mqtt-ros-bridge:
    container_name: mqtt-ros-bridge
    environment:
      - ROS_MASTER_URI=http://master:11311
    volumes:
      - .ros_logs/mqtt-ros-bridge:/root/.ros/
      - ./mqtt-bridge-configs:/mqtt-bridge-configs
    # because this container depends on mqtt
    # we add restart to the config so we dont
    # have to manually time deployment
    deploy:
      restart_policy:
        condition: any
        # delay: 5s
        # max_attempts: 10
    build:
      # context must be specified so that the Dockerfile gets access to the
      # top level directory that contains the mqtt-bridge-configs directory
      # https://stackoverflow.com/questions/47785706/docker-using-copy-when-the-dockerfile-is-located-in-a-subdirectory
      context: ./
      dockerfile: dockerfiles/mqtt-ros-bridge/Dockerfile
    command: roslaunch /mqtt-bridge-configs/mqtt_bridge.launch --wait

  # Required to install npm dependencies for the node-red container
  # The folder mounted here is shared between them
  # This container should be run before the node-red container
  install-node-red:
    image: node:latest
    volumes:
      - ./node-red-data/data:/data
    working_dir: /data
    command: npm install

  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
    volumes:
      - ./node-red-data/data:/data

  rosserial:
    container_name: rosserial
    environment:
      - ROS_MASTER_URI=http://master:11311
    ports:
      - "11411:11411"
    volumes:
      - .ros_logs/rosserial:/root/.ros/
      - ./rosserial-configs:/rosserial-configs
    build: dockerfiles/rosserial
    deploy:
      restart_policy:
        condition: any
    command: roslaunch /rosserial-configs/rosserial.launch --wait

  ros-groovy:
    container_name: ros-groovy
    tty: true
    build:
      context: ./dockerfiles/ros-groovy
      args:
        - BASE_IMAGE_NAME=ubuntu
        - BASE_IMAGE_TAG=bionic
        - VCS_REF=replace_with_commit_id
        - ROS_DISTRO=groovy

  differential-drive:
    container_name: differential-drive
    environment:
      - ROS_MASTER_URI=http://master:11311
    tty: true
    volumes:
      - .ros_logs/differential-drive:/root/.ros/
      - ./differential-drive-configs:/differential-drive-configs
    # image: ros:noetic-ros-base
    build:
      # context must be specified so that the Dockerfile gets access to the
      # top level directory that contains the mqtt-bridge-configs directory
      # https://stackoverflow.com/questions/47785706/docker-using-copy-when-the-dockerfile-is-located-in-a-subdirectory
      context: ./
      dockerfile: dockerfiles/differential-drive/Dockerfile
    # build: dockerfiles/differential-drive
    deploy:
      restart_policy:
        condition: any
