version: '3'

services:
  master:
    image: ros:noetic-ros-base
    tty: true
    container_name: catkin
    volumes:
      - ./:/working-directory
    working_dir: /working-directory
    command: /bin/bash
