version: '3'

services:
  talker:
    environment:
      - DISPLAY=localhost
    volumes:
      - .ros_logs/talker:/root/.ros/
    build: ./
    command: rosbag record -a

  listener:
    volumes:
      - .ros_logs/listener:/root/.ros/
    build: ./
    environment:
      - "PYTHONUNBUFFERED=1"
